module.exports = {
  extends: ['@commitlint/cli', '@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'docs',
        'style',
        'refactor:deps',
        'refactor:tests',
        'refactor:chore',
        'perf',
        'revert',
        'test',
        'ci',
        'build',
        'merge',
        'workflow',
        'release',
        'chore:deps',
        'chore:tests',
        'chore:chore',
        'chore:docs',
        'chore:style',
        'chore:refactor',
        'chore:perf',
        'chore:revert',
        'chore:test',
        'chore:ci',
        'chore:build',
        'chore:merge',
        'chore:workflow',
        'chore:release',
      ],
    ],
    'subject-case': [2, 'always', 'sentence-case'],
  },
};
